### ISSUE TITLE
Net 4.5 Version possible?

### ISSUE THREAD

**Issue by jogibear9988** [convertersystems/opc-ua-client#10]

**Comment by awcullen** [comment]
Possible, but not easily.  
I make good use of 4.6's  TcpClient, ConcurrentDictionary, and IConvertable.

**Comment by jogibear9988** [comment]
don't think that are 4.6 features. i have them in 4.5 also

**Comment by awcullen** [comment]
What is the benefit in supporting 4.5?

**Comment by jogibear9988** [comment]
would be easier for me, cause i don't need to modify my whole project! but as i looked now, maybe i change it completely to use 4.6.2

**Comment by awcullen** [comment]
It was easier to support 4.5 than I thought.
Please see Workstation.UaClient 1.5.1
