### ISSUE TITLE
License conflict-MIT vs RCL/GPL

### ISSUE THREAD

**Issue by mpostol** [convertersystems/opc-ua-client#132]
My concern is if the MIT license associated with the repository is not in conflict with the packages on the dependency graph, e.g. [`OPCFoundation.NetStandard.Opc.Ua`](http://opcfoundation.github.io/UA-.NETStandard/). I am not going to use this software but have my own OPC UA stuff and have the same problem. What do you think about it?

**Comment by awcullen** [comment]
Hi Mariusz,
Over the years, I have felt denial, anger, bargaining, depression and finally... acceptance, regarding the OPCF license terms. ;) Today, there are quite a few open projects I have used with good results.
At this time, this project only uses the OPCF code to test against.
By the way, I do enjoy reading your "OPC UA stuff".
BR,
Andrew
