### ISSUE TITLE
How to get all subscriptions (count) of the OPC Server

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#178]
Is it possible to ask the server how many subscriptions it currently holds?

I could count them myself when I subscribe. But if I have more than one client, it would not work that way anymore.

**Comment by awcullen** [comment]
Try reading the value of "i=2285" ( a.k.a Server_ServerDiagnostics_ServerDiagnosticsSummary_CurrentSubscriptionCount )
