### ISSUE TITLE
GetValueOrDefault for (array, list) ExtensionObject[]

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#179]
I want to read the `Server_ServerDiagnostics_SessionsDiagnosticsSummary_SessionDiagnosticsArray`. It's working but I don't know how to handle the result with the `GetValueOrDefault<>` to get the result.

Does the `GetValueOrDefault<>` actually support `arrays`  or `list<>`?

```csharp
// is null
var sessionList = readResponse.Results[1].GetValueOrDefault<List<SessionDiagnosticsDataType>>();

// is null
var sessionArray = readResponse.Results[1].GetValueOrDefault<SessionDiagnosticsDataType[]>();

// is working
var sessions = new List<SessionDiagnosticsDataType>();
if (readResponse.Results[1].Value is ExtensionObject[] extension)
{
	sessions = extension.Select(e => e.Body).Cast<SessionDiagnosticsDataType>().ToList();
}
```

![grafik](https://user-images.githubusercontent.com/17551597/101459665-d0dc9180-3938-11eb-8b6e-48c06d3b1db2.png)

![grafik](https://user-images.githubusercontent.com/17551597/101459703-de921700-3938-11eb-96cd-3babc4dafd1e.png)

**Comment by awcullen** [comment]
I would like to fix this in the next release.  Currently GetValueOrDefault  only supports T being object[] when DataValue holds ExtensionObject[].
