### ISSUE TITLE
Supporting Console Apps

### ISSUE THREAD

**Issue by ayman-metwally-developer** [convertersystems/opc-ua-client#180]
Greetings,

Sorry for the rude question. From the documentation I can see that Console Apps (.net framework) is not supported. Would that be supported in the near future? or the focus will be on the .net core only?

Thanks

**Comment by quinmars** [comment]
That's not a rude question at all. May I ask you where you have read that a .NET framework console app is not supported? UaClient is a netstandard2.0 library, so .NET framework is [supported with versions >= 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
