### ISSUE TITLE
Set custom subscription name

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#181]
Is it possible to set a custom subscription name when calling `CreateSubscriptionRequest`? I did not find any information about it.

opc ua diagnosis page of a SIEMENS S7-1516
![grafik](https://user-images.githubusercontent.com/17551597/102460268-0c691100-4047-11eb-896b-21851d3bdef9.png)

**Comment by awcullen** [comment]
Sorry @dojo90 ,  the server chooses the id and name shown above for diagnostics.  You do receive the Id in the service response when you call CreateSubscription.

**Comment by dojo90** [comment]
Ok thanks for the feedback. I almost thought so.
