### ISSUE TITLE
The attribute is not supported for the specified Node. (OPC_BAD_ATTRIBUTE_ID_INVALID) on SIMATIC S7-1200 OPC Server

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#189]
I have a `SIMATIC S7-1200` with the latest firmware `v4.4.1` and I would like to subscribe to the `Node` "`Event`":

![grafik](https://user-images.githubusercontent.com/17551597/109160538-355bff80-7776-11eb-972e-1fb49ca99a68.png)

However, when I subscribe to the node, I get the following error message:

>The attribute is not supported for the specified Node. (OPC_BAD_ATTRIBUTE_ID_INVALID)

Strangely, I get the same error with the "dataFEED OPC UA Client".

![grafik](https://user-images.githubusercontent.com/17551597/109161282-275aae80-7777-11eb-9ce9-95df8d67c79c.png)

I don't have this problem with a SIMATIC S7-1500. 

Can anyone confirm that this is a limitation of the 1200 series?

---

I would like to subscribe to the entire node in order to reduce the number of subscriptions, as otherwise I would need 4 subscriptions.

**Comment by awcullen** [comment]
It seems like you should be able to subscribe to the Value attribute.
Also, DataFeed can't _read_ the Value either.  A PLC would never return (null) value.

**Comment by dojo90** [comment]
The problem here is probably due to the opc server (1200 plc). I just couldn't subscribe to or read the datavalue because I got the mentioned error every time.
In this case, I will have to subscribe to each individual data point separately.

**Comment by dojo90** [comment]
@awcullen this Issue should be solved when using firmware `v4.5`

https://support.industry.siemens.com/cs/document/109793280/release-s7-1200-cpu-firmware-version-v4-5?dti=0&lc=en-WW

![grafik](https://user-images.githubusercontent.com/17551597/123617656-c4058980-d807-11eb-9a21-0fefb1788a54.png)
