### ISSUE TITLE
Siemens Timestamp to DateTime C#

### ISSUE THREAD

**Issue by franklupo** [convertersystems/opc-ua-client#193]
I use the Siemens timestamp and I get back an array that I need to convert to DateTime. I found these functions that I perform it. It would be nice if the helper functions were included in the project.

https://github.com/S7NetPlus/s7netplus/blob/develop/S7.Net/Types/DateTime.cs

**Comment by awcullen** [comment]
I am happy to learn about these helper functions.  Since these are specific to Siemens PLCs I think I should keep them separate from the opc ua library. Thanks for the suggestion.
