### ISSUE TITLE
Cannot connect to S7-1212C with Firmware >=v4.5.0

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#201]
The connection establishment fails after a short time with a channel `faulted event`:

![grafik](https://user-images.githubusercontent.com/17551597/121029083-98632680-c7a8-11eb-83ae-4d5f4dc8cba9.png)

A connection is still possible with the previous firmware version v4.4.1.

Can someone reproduce this phenomenon? I tested it with two different 1212C.

- https://support.industry.siemens.com/cs/document/107539748/firmware-update-f%C3%BCr-cpu-1212c-dc-dc-dc-8di-6do-2ai?dti=0&lc=en-US

---

With the `dataFEED OPC UA Demo Client` I'm able to connect and browse the CPU (https://industrial.softing.com/de/produkte/opc-ua-und-opc-classic-sdks/opc-ua-demo-client.html).

**Comment by awcullen** [comment]
I found the same issue when connecting to a S7-1215C with latest firmware 4.5.0.

I was able to fix it by specifying a much longer TimeoutHint.

```
                var channel = new UaTcpSessionChannel(
                    appDescription,
                    certificateStore,
                    new AnonymousIdentity(),
                    discoveryUrl,
                    options: new UaTcpSessionChannelOptions { TimeoutHint = 30000 });
```

The time to connect with secure channel is longer in this firmware.

Another way to go is to turn off encryption. 
```
                var channel = new UaTcpSessionChannel(
                    appDescription,
                    certificateStore,
                    new AnonymousIdentity(),
                    discoveryUrl,
                    securityPolicyUri: SecurityPolicyUris.None);
```
Then the connection time is immediate.
