### ISSUE TITLE
Incorrect or empty ServerTimestamp?

### ISSUE THREAD

**Issue by ShuhuaGao** [convertersystems/opc-ua-client#204]
Hi,

After reading a node, I inspected the `ServerTimestamp` and the `SourceTimestamp`. However, the `ServerTimestamp` seems to always be "0001/1/1 0:00:00".

- Read a node that simply yields random number
```cs
var randDataValue = readResult.Results[2];
Console.WriteLine("\nRandom node: ");
Console.WriteLine($"    Status: {randDataValue.StatusCode}");
Console.WriteLine($"    Value: {randDataValue.GetValueOrDefault<double>()}");
Console.WriteLine($"    Server timestamp: {randDataValue.ServerTimestamp}");
Console.WriteLine($"    Source timestamp: {randDataValue.SourceTimestamp}");
```
- The result is:
![image](https://user-images.githubusercontent.com/20141984/122899287-48768900-d37e-11eb-8e88-aef5c3f789d1.png)

- In the simulation server end, both timestamps are correct.
![image](https://user-images.githubusercontent.com/20141984/122899255-3f85b780-d37e-11eb-89f3-6c5f68275fe9.png)

Thanks for any help.

**Comment by awcullen** [comment]
Hi,

You can get both timestamps by setting a property of the CreateMonitoredItemsRequest.  

Example:
```
    var itemsRequest = new CreateMonitoredItemsRequest
    {
        SubscriptionId = id,
        ItemsToCreate = itemsToCreate,
        TimestampsToReturn = TimestampsToReturn.Both
    };

```

Best Regards,
Andrew

**Comment by ShuhuaGao** [comment]
Hi, Andrew. Many thanks.

By the way, could I ask you another question, since I am totally new to OPCUA? My application needs to read node information via OPCUA every 2 minutes. In that case, shall I keep the connection (i.e., a channel) open for the whole application's lifetime? Or should I close the channel once finishing the reading and then open it again next time (after 2 minutes)? Which one is the best practice in your opinion?
