### ISSUE TITLE
Unable to create NodeId - Cannot find type Workstation.ServiceModel.Ua.NodeId in module Workstation.UaClient.exe

### ISSUE THREAD

**Issue by avnet78** [convertersystems/opc-ua-client#211]
I am using Integration Obects' OPC UA Server Simulator and trying to read the nodes under Real Time Data, there are about 20 tags. I am able to create the session without any issues but for some reason I am unable to create the NodeId. 
As you can see in the code snippet below, I tried both NodeId.Parse and new Node(identifer, namespaceindex), but both are throwing an exception - Cannot find type Workstation.ServiceModel.Ua.NodeId in module Workstation.UaClient.exe..

Please help!

Here is my code:

```
var opcTags = new List<string> { "Tag1", "Tag2", "Tag3", "Tag4", "Tag5", "Tag6", "Tag7", "Tag8", "Tag9", "Tag10", "Tag11", "Tag12", "Tag13", "Tag14", "Tag15", "Tag16", "Tag17", "Tag18", "Tag19", "Tag20" };
var readValueIds = new List<ReadValueId>();

foreach (var item in opcTags)
{
    var tempId = $"ns=2;s={item}";
    var nodeId = NodeId.Parse(tempId); //new NodeId(item, 2);
    var readVal = new ReadValueId
    {
        NodeId = nodeId,
        AttributeId = AttributeIds.Value
    };
    readValueIds.Add(readVal);
}

// build a ReadRequest. See 'OPC UA Spec Part 4' paragraph 5.10.2
var readRequest = new ReadRequest
{
    // set the NodesToRead to an array of ReadValueIds.
    NodesToRead = readValueIds.ToArray()
};
// send the ReadRequest to the server.
var readResult = await channel.ReadAsync(readRequest);
```

![image](https://user-images.githubusercontent.com/63065740/129435905-c013e135-a3dc-4fa5-aea3-3302e0a3df13.png)

![image](https://user-images.githubusercontent.com/63065740/129437294-73e25a42-4e63-4c86-81f6-91b13d17538b.png)

![image](https://user-images.githubusercontent.com/63065740/129435909-666f9c50-b1db-4039-a5b2-a996af117e97.png)![image](https://user-images.githubusercontent.com/63065740/129436219-dd5dea1b-b474-464f-accb-f191ad691eb9.png)

**Comment by quinmars** [comment]
It looks like you are missing the `Workstation.UaClient.dll`. Usually visual studio copy it to your executable folder. You may want to check if it is actually present.

**Comment by awcullen** [comment]
It looks like QuickWatch window is having problem finding the NodeId type.  The application is finding the dll just fine, because it opened the session channel with server properly.

More importantly, I want to point out that the Ua Browser is showing the DisplayName of each node in the "Real Time Data" folder.  Often the NodeId is different from the DisplayName of a Node. The NodeId may be a String or Int (or sometimes a GUID or byte array).  All NodeIds must be unique in their namespace. You may find the server vendors use long strings in the NodeId to ensure they will be all unique, like "ns=3;s=AirConditioner_1.Temperature.EngineeringUnits".  

I would use a free tool such as UaExpert from UnifiedAutomation to discover the proper NodeId of the Nodes you wish to read.

**Comment by avnet78** [comment]
Installed UnifiedAutomation's UaExpert as suggested. I think the node id is "ns=2;s=Tag1". I am using the same node id in my code. Please advise!

![image](https://user-images.githubusercontent.com/63065740/129459036-0f3b744d-3022-4996-a0cb-d8ccd64288d8.png)

**Comment by avnet78** [comment]
Ok, I tried the old trick - ran the disk cleanup and restarted my machine. I can read the values now.
Some things don't change with Microsoft.  ;)

![image](https://user-images.githubusercontent.com/63065740/129459256-d860e9a1-a6c2-4967-95af-bf19a9714d84.png)

**Comment by avnet78** [comment]
Finally I was able to resolve the issue. 
I am not really sure but adding the below namespace dramatically fixed the issue. I was looking at your code samples realized that I didn't have this in my code. 
I am able to read the values for the OPC UA Server simulator. 

````using System.Reactive.Linq;````

![image](https://user-images.githubusercontent.com/63065740/129468652-baaee06c-2b12-46a5-a06c-bd74ff243635.png)
