### ISSUE TITLE
Connection to a TwinCAT OPC UA server in anonoumys mode

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [convertersystems/opc-ua-client#216]
How can a connection to a TwinCAT OPC UA server be established in anonoumys mode. Is TwinCAT supported?

**Comment by quinmars** [comment]
While I haven't tried it myself, there shouldn't be any difference to other OPC UA servers. Keep in mind, that you have to annotate your variables with [`{attribute 'OPC.UA.DA' := '1'}`](https://infosys.beckhoff.com/english.php?content=../content/1033/tcopcuaserver/117093590390367755.html&id=).

**Comment by ToGoOrNotToGo** [comment]
Thank you.
Yes, it's possible. However, the client resp. the certificate must be included in the trusted list.
