### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-client#24]
Can opc-ua-client be used in UWP applications ? According to this link, UWP supports only net-standard 1.4

[https://github.com/dotnet/standard/blob/master/docs/versions.md#net-standard-versions](url)

**Comment by awcullen** [comment]
Maybe you are seeing that I've referenced the .NETStandard package version 1.6.1?  Many people are confused. The package version and the target api version are different things. 

For an example of using opc-up-client with UWP see [https://github.com/convertersystems/opc-ua-samples/tree/master/RobotApp](RobotApp)
