### ISSUE TITLE
Can you please update the Nuget package?

### ISSUE THREAD

**Issue by Janaros** [convertersystems/opc-ua-client#254]
Hello,

thank you for your work!

We use the client in a project and had the problem that the server does not use a certificate. 
You have already fixed this in the master: https://github.com/convertersystems/opc-ua-client/pull/247

In Nuget Package 3.2.0 this fix is not yet included. It would be great if you could roll out an updated package.

thanks a lot!

**Comment by awcullen** [comment]
Glad you like the library.  I have updated the pkg to v3.2.1.
