### ISSUE TITLE
How To Subscribe to Arrays

### ISSUE THREAD

**Issue by kratostav** [convertersystems/opc-ua-client#261]
Hi,
first thank you for this great library.
I only have one Problem subscribing to an array in MVVM fashion. 
How to I subscribe and how to I get the Values to change in both directions?
Or do I have to flatten the arrays in multiple nodes?

**Comment by awcullen** [comment]
You can subscribe to whole arrays like below.  To change value at the PLC, you will have to set the property (write the whole array).   Changing a single element won't  work :( 

```

    /// <summary>
    /// Gets or sets the value of DemoStaticArraysUInt16.
    /// </summary>
    [MonitoredItem(nodeId: "ns=2;s=Demo.Static.Arrays.UInt16")]
    public UInt16[] DemoStaticArraysUInt16
    {
        get { return this._DemoStaticArraysVector; }
        set { this.SetProperty(ref this._DemoStaticArraysVector, value); }
    }

    private UInt16[] _DemoStaticArraysVector;
