### ISSUE TITLE
Could not connect to HTTPS endpoint

### ISSUE THREAD

**Issue by ondrejpazintelegrafia** [convertersystems/opc-ua-client#270]
Hello.
I could not manage to connect to HTTPS endpoint using this library. 
There is allways exception: 'Cannot access a disposed object. Object name: 'socket'.'

The exception is thrown even when using discovery service to find endpoints.

This is my code:
var getEndpointsRequest = new GetEndpointsRequest
{   
    EndpointUrl = "https://myPC:62641/IntegrationObjects/ServerSimulator/",
    ProfileUris = new[] { TransportProfileUris.HttpsXmlOrBinaryTransport },
};
var getEndpointsResponse = await DiscoveryService.GetEndpointsAsync(getEndpointsRequest);

**Comment by awcullen** [comment]
This package does not support HTTPS endpoints,  only OPC.TCP.  Sorry for confusion.

**Comment by ondrejpazintelegrafia** [comment]
Do you plan to support HTTPS endpoints in the future?

**Comment by awcullen** [comment]
I don't think so.  The OPC UA TCP binding with the binary encoding is fast and more widely available in industrial devices.
