### ISSUE TITLE
Server state change event & timeout events 

### ISSUE THREAD

**Issue by josetruyol-axys** [convertersystems/opc-ua-client#3]
Hi Andrew,

I noticed that there is no direct way to add a event listener to the ServerStateChange event. I had to do this in order to subscribe a listener to that event:
```
            PubSubEvent<CommunicationState> stateChangedEvent = session.GetEvent<PubSubEvent<CommunicationState>>();
            stateChangedEvent.Subscribe(OnStateChangeEvent);
```

Is this the intended way to do it or may be is there a possible that you expose some StateChanged event?

I have the same problem with timeout events, so I added an event handler to SubscriptionAdapter class:

```
        public event EventHandler WriteTimeout = null; 
```
And then modified the OnPropertyChanged method, adding 2 lines:
```
        private void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            ...

            MonitoredItemBase item;
            if (this.subscription.MonitoredItems.TryGetValueByName(e.PropertyName, out item))
            {
                var pi = item.Property;
                if (pi != null && pi.CanRead)
                {
                    var value = pi.GetValue(sender);
                    this.session.WriteAsync(new WriteRequest { NodesToWrite = new[] { new WriteValue { NodeId = item.NodeId, AttributeId = item.AttributeId, IndexRange = item.IndexRange, Value = value as DataValue ?? new DataValue(value) } } })
                        .ContinueWith(
                            t =>
                            {
                                foreach (var ex in t.Exception.InnerExceptions)
                                {
                                    Trace.TraceWarning($"Subscription error writing value for NodeId {item.NodeId}. {ex.Message}");
                                    if (WriteTimeout != null)                 <---
                                        WriteTimeout(item, EventArgs.Empty);  <---
                                }
                            }, TaskContinuationOptions.OnlyOnFaulted);
                }
            }
        }
```
Is there some event that notify this timeouts? That I didn't saw

Best Regards,
Jose

**Comment by awcullen** [comment]
Hello Jose,
The reason for having no direct way to add an event handler for session's StateChanged event is that we wanted to use weak references. In WPF and UAP, the views and viewModels are usually just abandoned by the shell when closed or navigated away.  The abandoned viewModels are garbage collected. When the Session detects this, it deletes the Subscription on the Server.  If I provide a public event on Session for StateChanged, it would be easy to add a handler in the viewModel and forget to remove it.  

Regarding write timeouts, I upgraded the UaClient  and Samples to enable a feature where the latest error detected when creating, publishing and writing the MonitoredItems are available in the Subscription.
In WPF, the error is displayed the same way validation errors are displayed. In UAP, there is no display.

![2016-08-28 1](https://cloud.githubusercontent.com/assets/11900570/18041384/22fb5b00-6d86-11e6-8f81-edbaf633b644.png)

Let me know if this solves your issue. I appreciate your feedback.

Andrew

**Comment by josetruyol-axys** [comment]
>  ... the views and viewModels are usually just abandoned by the shell when closed or navigated away ...

In this case, I will use only one view, without any kind of navigation. I guess that this will be not a issue, or I'm wrong?

>  I upgraded the UaClient and Samples to enable a feature where the latest error detected when creating,

I updated my project with your last commit, and I noticed the change on the ` ISubscription ` interface. Thanks for that!

Best Regarts,
José

**Comment by awcullen** [comment]
Hopefully this issue is solved. Feel free to reopen if there is still a problem.
