### ISSUE TITLE
issue in latest  release Nugets Workstation.UaClient - 1.5.12

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-client#34]
![image](https://cloud.githubusercontent.com/assets/25738779/25554002/58934786-2ce0-11e7-80a4-d72ec1126933.png)

I made Xamarin shared Mobile application in Android, iOS, UWP.
Application working fine with Nuget **Workstation.UaClient - 1.5.7**

When I Update Nuget to  **Workstation.UaClient - 1.5.12**  and rebuild same project then getting below errors in UWP application of xamarin 

As per attached screen shoot 

![image](https://cloud.githubusercontent.com/assets/25738779/25554037/251590b6-2ce1-11e7-821a-1d0b9de0cee0.png)

1. Error	CS0246	The type or namespace name 'LoggerFactory' could not be found 
2.  Error	Metadata	Error while reading ......#path#.......

Kindly help to resolve issue in stable release **Workstation.UaClient - 1.5.12** 

**Notes :**  In  **Workstation.UaClient - 1.5.12**  application working fine in Xamarin.Droid and Xamarin.iOS but issue is only in Xamarin.UWP application 

Thanks,

**Comment by awcullen** [comment]
The new version changed a package dependency from 'Microsoft.Extensions.Logging' to Microsoft.Extensions.Logging.Abstractions'.  The reason being that I was only using the interfaces. 

In your Droid, iOS, and UWP projects you should add a package reference to 'Microsoft.Extensions.Logging.Debug' if you wish to create a LoggerFactory.

Sorry for the confusion.

**Comment by tejasklodha** [comment]
Dear Sir,

Problem resolved when I install **Microsoft.Extensions.Logging** 

Thanks,
