### ISSUE TITLE
Fetch historical data of OPC UA from PLC?

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-client#37]
Dear Sir,

We want to access historical data of OPC UA from My PLC

**Practical scanario:**

One wpf application show live data from PLC throgh OPC UA.
somehow network connection break between PLC and my wpf application Now how can we face this issue?

can I fetch all historical data from PLC in view model?

I refer issue  https://github.com/convertersystems/opc-ua-client/issues/31

I try to run code as per attached file then unable to find historical data as below output.

![error](https://cloud.githubusercontent.com/assets/25738779/26619923/4a1ce126-45fe-11e7-8155-46cc7218c3a6.png)

[Program.zip](https://github.com/convertersystems/opc-ua-client/files/1040537/Program.zip)

Thanks

**Comment by awcullen** [comment]
Storage of historical data and events is not a feature of most OPC UA servers today. Hopefully that might change in future. However, today there is a product from ProSysOpc that would meet your needs:
https://www.prosysopc.com/products/opc-ua-historian/

**Comment by tejasklodha** [comment]
Dear Sir,

But I want to use in my code by using opc-ua-client.
Can it not possible from above code?

This is one of the most requirement in my current live project.

Thanks,

**Comment by awcullen** [comment]
Your code is good. I would check if (StatusCode.IsGood(result.StatusCode) to avoid the null exception. 

The main problem is that the sample RobotServer does not store/support historical data or historical events.  Most OPC UA servers do not, at this time. An exception is the OPC-UA-Historian from ProSysOpc, which essentially adds centralized storage of historical data and events from your existing UA servers.

An opc-ua-client would be configured to connect to the ProSysOpc historian when getting data for trending, reporting or alarm history.

**Comment by tejasklodha** [comment]
Dear sir,


Thanks for your response...
I will check our controller that, is it support to store historical data or not...

We are using b&r controller....

Thanks

**Comment by tejasklodha** [comment]
Right now unable to fetch historical data from my controller....
