### ISSUE TITLE
Request the current status of AlarmConditions 

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-client#42]
Does the opc-ua client have any possibility to request from the opc-ua server the current status of all AlarmConditions ? Could be useful to perform when the opc-ua client application starts.

**Comment by awcullen** [comment]
Nuget V2.0.2 has added helpful methods to SubscriptionBase:
```

public async Task<StatusCode> Acknowledge(AcknowledgeableCondition condition, LocalizedText comment = null);

public async Task<StatusCode> ConditionRefresh()

```
Also updated BaseEvent and subclasses, Added EventField attribute to properties to better control the generation of SelectClauses and deserialization. Please update your custom alarm classes.
