### ISSUE TITLE
Automatic Reconnection Logic

### ISSUE THREAD

**Issue by sbradford02** [convertersystems/opc-ua-client#44]
What is the proper way to re-establish a connection to the UA server from the UA client if it loses connection to the UA Server (Ethernet cable is unplugged for instance)?  Preferably keeping current subscriptions intact as well. 

When the cable is unplugged the UaTcpSessionChannel.State still shows as Opened and trying to recall UaTcpSessionChannel.OpenAsync() results in a "channel not modifiable" error.  Is the only way to recover to create a new session and resubscribe everything?

**Comment by awcullen** [comment]
Good question.  First, if the Ethernet cable unplugs or the Wifi drops out, you have some timeouts that can keep the session open for a while. There is a  SessionTimeout (default of 2 min).
```
var channel = new UaTcpSessionChannel(
    this.localDescription,
    this.certificateStore,
    selectedUserIdentity,
    selectedEndpoint,
    loggerFactory: this.loggerFactory,
    options: new UaTcpSessionChannelOptions { SessionTimeout = 120000 });
```
There is also a subscription timeout that is the product of PublishingInterval * LifetimeCount:
```
            var subscriptionRequest = new CreateSubscriptionRequest
            {
                RequestedPublishingInterval = 1000f,
                RequestedMaxKeepAliveCount = 30,
                RequestedLifetimeCount = 30 * 3,
                PublishingEnabled = true,
            };
```
If the interruption lasts longer than these timeouts then the SessionChannel and Subscriptions will need to be recreated. 

(There is a TransferSubscriptions method that you can use to transfer a subscription from a disconnected session to a new session. But I have found that many servers do not support it. )

If you take a look at the site https://github.com/convertersystems/opc-ua-samples, you will find the "StatusHmi" project that demonstrates a 'ViewModel' approach to building HMI's. This project will reconnect automatically.

 
![statushmi](https://user-images.githubusercontent.com/11900570/29235167-896f313a-7eca-11e7-90c6-cb1636436f9c.png)
