### ISSUE TITLE
Opc-ua client session StateChanged event

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-client#46]
In the earlier opc-ua client implementations there was an event "StateChanged" (in the UaTcpSessionClient class), that was triggered when the state of the connection to the opc-ua server changed.
Is this functionality also possible with SubscriptionBase ?

**Comment by awcullen** [comment]
There is a property of SubscriptionBase named State. You can listen to the PropertyChanged event.  The StatusHmi app demonstrates this by changing the title bar text.
