### ISSUE TITLE
uaclient 2.0.2: OpenAsync throws LocalPrivateKey is null?

### ISSUE THREAD

**Issue by basprins** [convertersystems/opc-ua-client#49]
Hi Andrew,

Maybe I am going to ask something really stupid this time, but I just got latest version of your library via nuget (2.0.2) and rewrote a small part of my code to correspond with the new interface:

                try
                {
                    var discoveryUrl = $"opc.tcp://{hostname}:{port}";

                    var appDescription = new ApplicationDescription
                    {
                        ApplicationName = "BR",
                        ApplicationUri = $"urn:{hostname}:4840",
                        ApplicationType = ApplicationType.Client
                    };

                    session = new UaTcpSessionChannel(
                        appDescription,
                        null,
                        GetAnonymousIdentityAsync,
                        new EndpointDescription { EndpointUrl = discoveryUrl, SecurityMode = MessageSecurityMode.None});

                    await session.OpenAsync();
                    break;
                }
                catch (Exception e)
                {
                    if (i >= RetryCounter)
                    {
                        throw new OpcUaCommunicationException(
                            $"Unable to connect to Opc UA server on '{hostname}:{port}' after retrying {RetryCounter} times",
                            e);
                    }
                    await Task.Delay(3000);
                }

And the static async method to give an anonymous identity:

        private static async Task<IUserIdentity> GetAnonymousIdentityAsync(EndpointDescription endpoint)
        {
            return new AnonymousIdentity();
        }

But I get the exception "LocalPrivateKey is null".

When I check your source code, it checks the RemoteEndpoint.SecurityMode (which is set to None in my case) and should go into the branch where a bunch of defaults are set. 

I'd expect that the following code would execute in your library

            else if (this.RemoteEndpoint.SecurityMode == MessageSecurityMode.None)
            {
                this.asymIsSigned = this.asymIsEncrypted = false;
                this.symIsSigned = this.symIsEncrypted = false;
                this.asymLocalKeySize = 0;
                this.asymRemoteKeySize = 0;
                this.asymLocalSignatureSize = 0;
                this.asymLocalCipherTextBlockSize = 1;
                this.asymRemoteSignatureSize = 0;
                this.asymRemoteCipherTextBlockSize = 1;
                this.asymLocalPlainTextBlockSize = 1;
                this.asymRemotePlainTextBlockSize = 1;
                this.symSignatureSize = 0;
                this.symSignatureKeySize = 0;
                this.symEncryptionBlockSize = 1;
                this.symEncryptionKeySize = 0;
                this.encryptionBuffer = null;
}
How can I still get the exception? What should I pass in the constructor to avoid this from happening?

Thanks.

**Comment by awcullen** [comment]
Hi,

You can use the following to select an endpoint without security. Sorry for lack of documentation!   
```
var session = new UaTcpSessionChannel(
                  this.localDescription,
                  null,
                  GetAnonymousIdentityAsync,
                  new EndpointDescription { EndpointUrl = EndpointUrl, SecurityPolicyUri = SecurityPolicyUris.None });
```

Andrew

**Comment by basprins** [comment]
Thanks!
