### ISSUE TITLE
Release notes 2.1?

### ISSUE THREAD

**Issue by basprins** [convertersystems/opc-ua-client#51]
Hey Andrew,

any chance we can read back to highlights of changes/fixes from 2.0.2 to 2.1? Browsed around in your github pages but couldn't find anything. 

Thanks in advance.

**Comment by awcullen** [comment]
Release notes would be helpful!
Highlights from 2.0.2 to 2.1:
Upgraded some package dependencies.
Fixed some bugs regarding ExpandedNodeId and ExtensionObject for the purpose of reading/writing structured data types that are available on my Siemens S7-1500. More work is needed.
Added support for .NETStandard 2.0. Removed support for .NETFramework 4.5

**Comment by basprins** [comment]
Thanks a lot 👍
