### ISSUE TITLE
Error on Compile in New Solution - Key.cs' is a binary file instead of a text file

### ISSUE THREAD

**Issue by arobinsongit** [convertersystems/opc-ua-client#58]
When trying to include the UAClient project in an existing solution I get this error on first compile.

'D:\localrepo\icstesting\Console\UaClient\Key.cs' is a binary file instead of a text file

Steps to recreate
1) Perform a git clone from repo into a clean folder
2) Compile solution - success
3) Copy only UAClient folder into existing solution
4) Compile solution - error above received

As I don't have a a lot of experience with code signing I'm suspecting this is a basic issue of not doing something correctly.

**Comment by awcullen** [comment]
The easiest way to use the library is to add the NuGet package "Workstation.UaClient" to your project.
Right click on the "References" folder and select "Manage NuGet Packages...".  Select the "Browse" tab and search for "Workstation.UaClient".  Select the package and click "Install". The library and all the necessary .dll's are added to your project.

In the project source, there is a "Key.snk" file that is used for signing the assembly. 
If you are compiling your own assembly, you should remove it.
