### ISSUE TITLE
The user identity of X509Identity is not implemented. Why?

### ISSUE THREAD

**Issue by ggokka** [convertersystems/opc-ua-client#62]
I've found the X509Identity is not implemented.

--UaTcpSessionChannel.cs
 else if (this.UserIdentity is X509Identity)
            {
                throw new NotImplementedException("A user identity of X509Identity is not implemented.");
                /*
                var tokenPolicy = this.RemoteEndpoint.UserIdentityTokens.FirstOrDefault(t => t.TokenType == UserTokenType.Certificate);
                if (tokenPolicy == null)
                {
                    throw new ServiceResultException(StatusCodes.BadIdentityTokenRejected);
                }

**Comment by awcullen** [comment]
I added support for X509Identity - a user identity associated with a x509 certificate.  
You can see how to parse a certificate and a private key in the Unit Tests.
