### ISSUE TITLE
Any planing with the framework for the future?

### ISSUE THREAD

**Issue by OmidID** [convertersystems/opc-ua-client#63]
I can see the last push for 10 months ago it is.
Do you have any plan for update and release it for other platforms ?

**Comment by awcullen** [comment]
Hello,
Indeed, it is a good time for an update.  The Opc UA specification has been updated to v1.04 with many new features.  New session-less services,  improved methods for describing a custom data structure, and PubSub.  What new features or platforms would be useful to you?

**Comment by OmidID** [comment]
Hello,
As you know .NetFx will be replace with .Net Core so i suggest to support .Net Standard Library.
For the moment we are using Mono + Linux-ARM and we thinking to use your library as client.
And we will upgrade to .Net Core for next generation.
By the way we are using self-signed certificate and it's would be perfect to support custom certificate authorization.
Thanks.
