### ISSUE TITLE
Create a OPC UA Server

### ISSUE THREAD

**Issue by jogibear9988** [convertersystems/opc-ua-client#68]
Is it possible to use your Code as a Start for writing a OPC UA Server?

Is there any Free Documentation about OPC UA available?

**Comment by awcullen** [comment]
Hi jogibear,

It's good to hear from you.
I don't believe this code would be a good start for a UA server. Maybe someday. The free documentation at the foundation is all I use:
https://opcfoundation.org/developer-tools/specifications-unified-architecture

My colleagues use https://www.unified-automation.com/

Andrew
