### ISSUE TITLE
PublishResponse notificate StatusChangeNotification instead of DataChangeNotification

### ISSUE THREAD

**Issue by iocio005** [convertersystems/opc-ua-client#76]
When I'm debugging my application with this library I recieve a StatusChangeNotification instead of DataChangeNotification in my SubscriptionObserver.cs.

This also happen when the applications becomes slowly for example because I am processing a large amount of data

    public virtual void OnNext(PublishResponse value)
        {
            var notifications = value.NotificationMessage.NotificationData;
            if (notifications != null)
            {
                foreach (var notif in notifications)
                {
                    try
                    {
                        // System.InvalidCastException:
                        // Cannot cast from 'Workstation.ServiceModel.Ua.StatusChangeNotification' to 'Workstation.ServiceModel.Ua.DataChangeNotification'
                        var notification = (DataChangeNotification)notif;
                        foreach (var itemNotif in notification.MonitoredItems)
                        {
                            OnItemChangeNotification(itemNotif);
                        }
                    }
                    catch (Exception e)
                    {
                        console.LogError($"Notification error: {e.ToString()}");
                        console.LogError($"Notification item: {notif.ToString()}");
                    }
                }
            }
        }

I'm thinking to protect with an 

    if (notif.GetType() == typeof(DataChangeNotification))

before of casting but I'm not sure if this is the best way to accomplish that.

When or why is it happen that OPC Server notifies me with a statuschange notification? Are these (StatusChangeNotification) notification safe to wrap hoping that the communication is going to continue right after that?

Thank you very much.

**Comment by awcullen** [comment]
Hi Iocio,
The NotificationData array may contain DataChangeNotifications, EventNotificationLists and StatusChangeNotifications.  So I sort it out:
```
    // loop thru all the data change notifications
    var dcns = pr.NotificationMessage.NotificationData.OfType<DataChangeNotification>();
    foreach (var dcn in dcns)
    {
        foreach (var min in dcn.MonitoredItems)
        {
            Console.WriteLine($"sub: {pr.SubscriptionId}; handle: {min.ClientHandle}; value: {min.Value}");
        }
    }
    // loop thru all the event notifications
    var enls = pr.NotificationMessage.NotificationData.OfType<EventNotificationList>();
    foreach (var enl in enls)
    {
        foreach (var efl in enl.Events)
        {
            var ev = EventHelper.Deserialize<BaseEvent>(efl.EventFields);
            Console.WriteLine($"time: {ev.Time}, src: {ev.SourceName}, msg: {ev.Message}, sev: {ev.Severity}");
        }
    }

```
