### ISSUE TITLE
Channel closed when "The session cannot be used because ActivateSession has not been called." has thrown

### ISSUE THREAD

**Issue by iocio005** [convertersystems/opc-ua-client#81]
Hi.

I have 12 OPC client subscription with 12 B&R PLC.
Sometimes I lose the events that I am monitoring. Here you have the exception that I caught:

[OPC Exception.txt](https://github.com/convertersystems/opc-ua-client/files/3240581/OPC.Exception.txt)

Something like ` Error publishing subscription. The session cannot be used because ActivateSession has not been called.` and then `The session id is not valid`.

I do not understand why I lose connection because I have this reconnection logic in my class:

    private void OnChannelFaulted(object sender, EventArgs e) 
    {
        console.LogWarning($"{StationHeader} Connection fault");
        if (started)
        {
            Task.Factory.StartNew(this.WaitAndConnectAsync);
        }
    }

and

    private async Task WaitAndConnectAsync()
    {
        console.LogDebug($"{StationHeader} Waiting {ReconnectionIntervalSecs}s for connection retry...");
        await Task.Delay(ReconnectionIntervalSecs * 1000).ConfigureAwait(false);
        await ConnectAsync().ConfigureAwait(false);
    }

that in normal "reconnection" works fine.

Could you give me some clue about what I have to find it?

**Comment by awcullen** [comment]
Sorry Iker, did you find a solution to this problem?
In general, I did not plan for a existing channel to re-connect after fault.
I normally would recommend to create a new channel. (this I learned from the old WCF days...)

Andrew
