### ISSUE TITLE
The user identity token is not valid

### ISSUE THREAD

**Issue by mcsreddy17** [convertersystems/opc-ua-client#83]
Hi, thank you for all your work. Currently, I'm trying to test out username and password support by creating my own opc client, and I'm seeing the following error when calling 'await channel.OpenAsync()' on the client.

Error: [0x80200000]="The user identity token is not valid.

**Comment by awcullen** [comment]
I would test connecting with this username and password using a tool such as OPCExpert by Unified Automation.

**Comment by mcsreddy17** [comment]
It is working with OPCUAExpert tool. In fact,

**Comment by awcullen** [comment]
Okay.  Could you test if this occurs when using SecurityPolicy None and when using Basic256Sha256?

**Comment by awcullen** [comment]
If this is still an problem, please reopen issue.

**Comment by ricardosousa1231** [comment]
same problem, it still occurs with both security policies

**Comment by awcullen** [comment]
Hi, 
Would you share some more details of the problem?  What is the server your connecting to? What is the SecurityPolicy? What error are you receiving?
Today I test the software with UnifiedAutomation's UaCPPServer, using username/password authentication  with all five security policies.  All is connecting correctly.

Thank you

**Comment by awcullen** [comment]
started new issue #168

**Comment by ricardosousa1231** [comment]
well , I am connecting through a VPN to a client's server. If I host a server on my computer it works too for me. I don't know if the problem is the server or the connection ...

**Comment by krstev89** [comment]
> Hi, thank you for all your work. Currently, I'm trying to test out username and password support by creating my own opc client, and I'm seeing the following error when calling 'await channel.OpenAsync()' on the client.
> 
> Error: [0x80200000]="The user identity token is not valid.

did you fix the issue. I have the same problem and can not understand what is causing it.

**Comment by ans-mindsandco** [comment]
I also have the problem. I can connect with UA Expert, but if i use prosys browser client, then i get the Bad_IdentityTokenInvalid
