### ISSUE TITLE
FileLoadException

### ISSUE THREAD

**Issue by basprins** [convertersystems/opc-ua-client#86]
Hi Andrew,
Sorry to keep bugging you, but you closed my [previous issue](https://github.com/convertersystems/opc-ua-client/issues/84) which I commented on more. I am not sure if you still receive notifications on that topic since it's closed. Could you let me know if you can have a look please? If you can't support on it, I will look elsewhere.

Many thanks in advance

**Comment by awcullen** [comment]
Sorry about closing this issue. I have upgraded the Dataflow package to 4.9.
Look for the version 2.3.0 in Nuget soon.

**Comment by basprins** [comment]
2.3.0 solves the issue! thanks!
